version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
#      - export $(grep -v '^#' ./.env | xargs)
      - ./gradlew clean
      - echo ">>> Creating .env file..."
      - echo "JWT_SECRET=${JWT_SECRET}" > .env
      - echo "JWT_TIME=${JWT_TIME}" >> .env
      - echo "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}" >> .env
      - echo "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}" >> .env
      - echo "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}" >> .env
      - echo "STRIPE_WEBHOOK_KEY=${STRIPE_WEBHOOK_KEY}" >> .env
      - echo "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}" >> .env
      - echo "EMAIL_USERNAME=${EMAIL_USERNAME}" >> .env
      - echo "EMAIL_PASSWORD=${EMAIL_PASSWORD}" >> .env
      - echo ".env file created:"

  build:
    commands:
      - echo ">>> Building jar..."
      - ./gradlew bootJar --no-daemon
  post_build:
    commands:
      - echo ">>> Build completed. Packaging for deployment..." > logs

artifacts:
  files:
    - .env
    - build/libs/*.jar
    - appspec.yml
    - scripts/**/*