version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo ">>> Cleaning project..."
      - ./gradlew clean
  build:
    commands:
      - echo ">>> Building jar with environment variables..."
      - ./gradlew bootJar --no-daemon -Djwt.secret=$JWT_SECRET -Djwt.time=$JWT_TIME -Dstripe.secret.key=$STRIPE_SECRET_KEY
  post_build:
    commands:
      - echo ">>> Build completed. Packaging for deployment..."

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - scripts/**/*
    - Dockerfile
  discard-paths: no
