# ==========================
# Application-Prod
# ==========================
spring.application.name=happy-beans
server.port=80

# ==========================
# JWT Security
# ==========================
security.jwt.token.secret-key=${JWT_SECRET}
security.jwt.token.expire-length=${JWT_TIME}

# ==========================
# Datasource
# ==========================
spring.datasource.url=jdbc:postgresql://rds-happy-beans.cqsc6pyqhwww.ap-northeast-2.rds.amazonaws.com:5432/happy-beans?currentSchema=happy_beans_schema
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hikari settings
spring.datasource.hikari.auto-commit=false

# ==========================
# JPA / Hibernate
# ==========================
## Disable Hibernate automatic DDL; we use schema.sql
spring.jpa.hibernate.ddl-auto=validate

# Format SQL for readability
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=false

# Enable Spring Boot SQL initialization
spring.sql.init.mode=always
spring.sql.init.platform=postgresql

# ==========================
# Stripe
# ==========================
stripe.apiKey=${STRIPE_SECRET_KEY}
stripe.webhookKey=${STRIPE_WEBHOOK_KEY}

# ==========================
# Mail
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

# ==========================
# Optional config import
# ==========================
spring.config.import=optional:file:.env[.properties]
