-- ==========================
-- Happy Beans Postgres Schema (Hibernate-friendly, Fixed)
-- ==========================

-- ==========================
-- USERS
-- ==========================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('ADMIN','RESTAURANT_OWNER','USER'))
);

-- ==========================
-- RESTAURANTS
-- ==========================
CREATE TABLE IF NOT EXISTS restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    user_id BIGINT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    address_url VARCHAR(255),
    image VARCHAR(255),
    CONSTRAINT fk_restaurant_user FOREIGN KEY (user_id) REFERENCES users
);

-- ==========================
-- DISHES
-- ==========================
CREATE TABLE IF NOT EXISTS dishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    restaurant_id BIGINT,
    description VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_dish_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants
);

-- ==========================
-- DISH OPTIONS
-- ==========================
CREATE TABLE IF NOT EXISTS dish_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available BOOLEAN NOT NULL,
    prep_time_minute INTEGER,
    price FLOAT(53) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    image VARCHAR(255) NOT NULL,
    dish_id BIGINT,
    CONSTRAINT fk_dish_option_dish FOREIGN KEY (dish_id) REFERENCES dishes
);

-- ==========================
-- CART PRODUCTS
-- ==========================
CREATE TABLE IF NOT EXISTS cart_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    quantity INTEGER NOT NULL,
    dish_id BIGINT NOT NULL,
    dish_option_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT uq_cart_user_dish_option UNIQUE (user_id, dish_option_id),
    CONSTRAINT fk_cart_dish FOREIGN KEY (dish_id) REFERENCES dishes,
    CONSTRAINT fk_cart_dish_option FOREIGN KEY (dish_option_id) REFERENCES dish_options,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users
);

-- ==========================
-- TAGS
-- ==========================
CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    name VARCHAR(255) NOT NULL UNIQUE
);

-- ==========================
-- DISH OPTION TAGS (Many-to-Many)
-- ==========================
CREATE TABLE IF NOT EXISTS dish_option_tags (
    dish_option_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (dish_option_id, tag_id),
    CONSTRAINT fk_dish_option_tags_dish_option FOREIGN KEY (dish_option_id) REFERENCES dish_options,
    CONSTRAINT fk_dish_option_tags_tag FOREIGN KEY (tag_id) REFERENCES tags
);

-- ==========================
-- USER LIKES TAGS (Many-to-Many)
-- ==========================
CREATE TABLE IF NOT EXISTS user_likes_tags (
    tag_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (tag_id, user_id),
    CONSTRAINT fk_user_likes_tag FOREIGN KEY (tag_id) REFERENCES tags,
    CONSTRAINT fk_user_likes_user FOREIGN KEY (user_id) REFERENCES users
);

-- ==========================
-- USER DISLIKES TAGS (Many-to-Many)
-- ==========================
CREATE TABLE IF NOT EXISTS user_dislikes_tags (
    tag_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (tag_id, user_id),
    CONSTRAINT fk_user_dislikes_tag FOREIGN KEY (tag_id) REFERENCES tags,
    CONSTRAINT fk_user_dislikes_user FOREIGN KEY (user_id) REFERENCES users
);

-- ==========================
-- ORDERS
-- ==========================
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    total_amount FLOAT(53) NOT NULL,
    user_id BIGINT NOT NULL,
    payment_id VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    creation_source VARCHAR(50) NOT NULL CHECK (creation_source IN ('AUTO','USER')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('CANCELLED','COMPLETED','PENDING','REJECTED'))
);

-- ==========================
-- ORDER PRODUCT
-- ==========================
CREATE TABLE IF NOT EXISTS order_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    price FLOAT(53) NOT NULL,
    quantity INTEGER NOT NULL,
    dish_option_id BIGINT,
    dish_name VARCHAR(255),
    orders_id BIGINT NOT NULL,
    CONSTRAINT fk_order_product_order FOREIGN KEY (orders_id) REFERENCES orders
);

-- ==========================
-- PAYMENT
-- ==========================
CREATE TABLE IF NOT EXISTS payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    amount FLOAT(53) NOT NULL,
    currency VARCHAR(255) NOT NULL,
    order_id BIGINT NOT NULL,
    session_id VARCHAR(255) NOT NULL,
    payment_option VARCHAR(50) NOT NULL CHECK (payment_option IN ('STRIPE')),
    status VARCHAR(50) NOT NULL CHECK (status IN ('COMPLETED','FAILED','IN_PROGRESS')),
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders
);

-- ==========================
-- RESTAURANT WORKING DATES & HOURS
-- ==========================
CREATE TABLE IF NOT EXISTS restaurant_working_dates_hours (
    restaurant_id BIGINT NOT NULL,
    open_time TIME(6) NOT NULL,
    close_time TIME(6) NOT NULL,
    day_of_week VARCHAR(50) NOT NULL CHECK (day_of_week IN ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    CONSTRAINT fk_restaurant_hours FOREIGN KEY (restaurant_id) REFERENCES restaurants
);

-- ==========================
-- RESTAURANT REVIEW
-- ==========================
CREATE TABLE IF NOT EXISTS restaurant_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    message VARCHAR(255),
    rating FLOAT(53) NOT NULL,
    restaurant_id BIGINT,
    restaurant_name VARCHAR(255),
    user_id BIGINT NOT NULL,
    user_name VARCHAR(255) NOT NULL
);

-- ==========================
-- DISH REVIEW
-- ==========================
CREATE TABLE IF NOT EXISTS dish_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    dish_option_id BIGINT,
    dish_option_name VARCHAR(255),
    dish_option_price FLOAT(53),
    message VARCHAR(255),
    rating FLOAT(53) NOT NULL,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(255) NOT NULL
);

-- ==========================
-- JOIN REQUEST
-- ==========================
CREATE TABLE IF NOT EXISTS join_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    email VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    message VARCHAR(255),
    status VARCHAR(50) NOT NULL CHECK (status IN ('INVITATION_SENT','PENDING','REJECTED'))
);

-- ==========================
-- Indexes
-- ==========================
CREATE INDEX IF NOT EXISTS idx_tag_name ON tags (name);
